name: Release assets

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install x86_64-unknown-linux-musl
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    
    - name: Install i686-unknown-linux-musl
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: i686-unknown-linux-musl
        override: true
    
    - name: Build x86_64
      run: RUSTFLAGS='-C link-arg=-s' cargo build --release --target x86_64-unknown-linux-musl
      
    - name: Create changelog
      uses: saadmk11/changelog-ci@v0.7.0
      with:
        changelog_filename: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build i686
      run: RUSTFLAGS='-C link-arg=-s' cargo build --release --target i686-unknown-linux-musl
      
    - name: Rename artifacts
      run: |
         mv target/x86_64-unknown-linux-musl/release/rusty-magisk target/x86_64-unknown-linux-musl/release/rusty-magisk_x86_64
         mv target/i686-unknown-linux-musl/release/rusty-magisk target/i686-unknown-linux-musl/release/rusty-magisk_x86
      
    - name: Release artifacts
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "true"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "true"
      with:
        args: |
            target/*-unknown-linux-musl/release/rusty-magisk*
